
trigger:
- develop


pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
  script: dotnet build --configuaration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
