trigger:
- task: Bash@3
  inputs:
- develop
- feature/*
- master

pool:
  name: 'Demo'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build---configuration.$(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
 